layout_spectrum: 0.6133371354080737
typography_spectrum: 0.3059272258542478
color:
  brandStrength: 0.9687599097378552
  lightness: 0.6466591770295054
  saturation: 0.4060789574868977
  rhythmicContrast: 0.5640165817458183
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
name: Skamfu True
